#!/bin/sh

FILE=~/docs/Anglish.tsv

from() {
    grep "^$*" $FILE
}

to() {
    grep "\\t$*" $FILE
    grep "\\ta  $*" $FILE
    grep "\\tan $*" $FILE
    grep "; $*" $FILE
    grep "; a  $*" $FILE
    grep "; an $*" $FILE
}

case $1 in
    t*) shift; to   "$*" ;;
    f*) shift; from "$*" ;;
    *)  echo "Usage: $0 to/from [WORD]" ;;
esac
