#!/bin/sh

FILE=~/docs/Anglish.tsv

from() {
    grep -i "^$*" $FILE
}

find() {
	grep -i "᛫ $*" $FILE
	grep -i "᛬ $*" $FILE
}

to() {
    find "$*"
    find "a $*"
    find "an $*"
    find "to $*"
}

case $1 in
    t*) shift; to   "$*" ;;
    f*) shift; from "$*" ;;
    a*) shift; to "$*"; from "$*"; true ;;
    *)  echo "Usage: $0 to/from [WORD]" ;;
esac
