#!/bin/sh

[ "$*" = "" ] && echo "Usage: $0 [+/-]N%" && exit

setvol()
{
	amixer sset Master "$*"
}

setvol "$@"
vol=$(amixer get Master | awk '/%/ { print $5 }' | tr -d '[]%' | uniq)
bar=$(seq -s "─" "$((vol/3))" | tr -d '0-9')
mute=$(amixer get 'Master' | awk '/%/ { print $6 }' | tr '[]' ' ' | uniq)

urgency=normal
if [ "$mute" = "off" ]; then
	:
elif [ "$vol" -lt "25" ]; then
    urgency=low
elif [ "$vol" -lt "50" ]; then
    urgency=normal
else
    urgency=critical
fi

if command -v dunstify > /dev/null 2> /dev/null; then
    dunstify -u "$urgency" -r 1 -- "$bar"
fi
