#!/bin/sh

URL=https://api.thevirustracker.com/free-api?global=stats
FILE=/tmp/covid19.json
TMPFILE=/tmp/covid19_tmp.json

fetch() {
    touch $TMPFILE
    curl -s $URL -o $TMPFILE
    mv $TMPFILE $FILE
}

cleanup() {
    rm -f $FILE
}

total() {
    jq -M ".results[].total_$1" < $FILE | paste -sd+ | bc
}

confirmed() { echo "$(total cases) C"; }
active()    { echo "$(total unresolved) A"; }
dead()      { echo "$(total deaths) D"; }
recovered() { echo "$(total recovered) R"; }

cases() {
    echo "$(confirmed)   $(dead)   $(active)   $(recovered)"
}

fatality_rate() {
    echo "$(total deaths) / $(total confirmed) * 100" | bc -l
}

case $1 in
    fetch) [ -f $TMPFILE ] || fetch ;;
    "") printf "%s   %0.2f%%\\r\\n" "$(cases)" "$(fatality_rate)" ;;
    *) total "$1" ;;
esac
