#!/bin/sh

URL=https://covid2019-api.herokuapp.com/total
FILE=/tmp/covid19.json
TMPFILE=/tmp/covid19_tmp.json

fetch() {
    touch $TMPFILE
    curl -s $URL -o $TMPFILE
    mv $TMPFILE $FILE
}

cleanup() {
    rm -f $FILE
}

total() {
    jq -M ".$1" < $FILE
}

total_active() {
    echo $(($(total confirmed) - $(total dead) - $(total recovered)))
}

confirmed() { echo "$(total confirmed) C"; }
active()    { echo "$(total_active) A"; }
dead()      { echo "$(total deaths) D"; }
recovered() { echo "$(total recovered) R"; }

cases() {
    echo "$(confirmed)   $(active)   $(dead)   $(recovered)"
}

fatality_rate() {
    echo "$(total deaths) / $(total confirmed) * 100" | bc -l
}

fchif() {
    [ -f $FILE ] || fetch
}

case $1 in
    fetch) [ -f $TMPFILE ] || fetch ;;
    "")  fchif; printf "%s   %0.2f%%\\r\\n" "$(cases)" "$(fatality_rate)" ;;
    get) fchif; total "$2" ;;
    *)
        echo "Usage: $0"
        echo "       $0 get [statistic]"
        ;;
esac
