#!/bin/sh -e

IN="$1"
OUT="$2"
[ "$OUT" ] || OUT="$(echo "$IN" | sed -E 's/\.(txt|md)$//').htm"

md() {
	markdown -ffootnote,autolink
}

htm() {
	title="$(sed '1d;2s/^ *//;q' "$1")"
	subtitle="$(sed '1,2d;3s/^ *//;q' "$1")"
	date="$(sed '1s/^ *//;q' "$1")"
	body="$(sed -e '1,3d;s/^         *\(.*\)$/## \1/'\
		-e 's/^(\([^()]*\)):$/<p class="section">\1<\/p>/' "$1" | md)"

	cat << EOF
<!DOCTYPE html>

<html lang="en">
	<head>
		<title>$title</title>
		<meta charset="UTF-8" />
		<style>$(min < "$HOME/.css")</style>
	</head>

	<body>
		<main>
			<article>
				<header>
					<p class="date">$date</p>
					<h1 class="title">$title</h1>
$(if [ "$subtitle" ]; then echo "\t\t\t\t\t<p class=\"subtitle\">$subtitle</p>"; fi)
				</header>

$body
			</article>
		</main>
	</body>
</html>
EOF
}

PID=0

bye() {
	[ "$PID" != 0 ] && kill "$PID"
	killall surf
}

trap bye KILL EXIT TERM

while true; do
	if [ -f "$IN" ]; then
		htm "$IN" > "$OUT"
		if [ "$DISPLAY" ]; then
			if pgrep -x surf; then
				killall -SIGHUP surf
			else
				nohup surf "file://$(realpath "$OUT")" &
			fi
		fi
		inotifywait -qqe modify "$IN" "$HOME/.css"
	fi
done > /dev/null 2> /dev/null &

PID="$!"
vi "$1"
