#!/bin/sh -e

IN="$1"
OUT="$(echo "$IN" | sed -E 's/\.(txt|md)$//').htm"

htm() {
	title="$(sed '1d;2s/^ *//;q' "$1")"
	date="$(sed '1s/^ *//;q' "$1")"
	body="$(sed '1,2d;s/^         *\(.*\)$/## \1/;s/^	\(.*\)$/### \1/' "$1" | markdown\
		| sed 's/^/				/')"

	cat << EOF
<!DOCTYPE html>

<html lang="en">
	<head>
		<title>$title</title>
		<meta charset="UTF-8" />
		<link rel="stylesheet" href="/style.css" />
	</head>

	<body>
		<main>
			<article>
				<header>
					<p class="date">$date</p>
					<h1 class="title">$title</h1>
				</header>

$body
			</article>
		</main>
	</body>
</html>
EOF
}

pid=0

bye() {
	[ "$pid" != 0 ] && kill "$pid"
}

trap bye KILL EXIT TERM

while true; do
	if [ -f "$IN" ]; then
		inotifywait -qq "$IN"
		htm "$IN" > "$OUT"
		if [ "$DISPLAY" ]; then
			if pgrep -x surf; then
				killall -SIGHUP surf
			else
				xdotool key alt+Tab ctrl+r alt+Tab
			fi
		fi
	fi
done > /dev/null 2> /dev/null &

pid="$!"
vi "$1"
