#!/bin/sh

vbib "$1" > /dev/null 2> /dev/null &
vpid=$!

cleanup() {
	echo "goodbye"
	pkill -P $$
}

trap cleanup EXIT

inotifywait -qme CLOSE_WRITE "$1" | while read event; do
	kill -HUP $vpid
done &

[ -f "$1" ] || echo '\\beginsection\n\n\\bye' > "$1"
nvi "$1"
