#!/bin/sh

vtex "$1" > /dev/null 2> /dev/null &
vpid=$!

updpid=0

cleanup() {
	echo "goodbye"
	echo kill -INT $vpid
	kill $vpid
	kill $updpid
}

trap cleanup EXIT

inotifywait -qme CLOSE_WRITE "$1" | while read event; do
	kill -HUP $vpid
done &
updpid=$!

[ -f "$1" ] || echo '\\beginsection\n\n\\bye' > "$1"
nvi "$1"
