#!/bin/sh

ADDR='34:43:16:04:41:63'

PROMPT="Bluetooth headphones [$ADDR]"

OPTON="Connect"
OPTOFF="Disconnect"
OPTEXIT="[ Cancel ]"

options() {
    echo "$OPTON"
    echo "$OPTOFF"
    echo "$OPTEXIT"
}

on() {
    echo "power on" | bluetoothctl
    sleep 1
    echo "connect ${ADDR}" | bluetoothctl
}

off() {
    echo "power off" | bluetoothctl
}

loop() {
    while true; do
        opt=$(options | menu -i -p "$PROMPT")
        case "$opt" in
            "$OPTON")  on  & ;;
            "$OPTOFF") off & ;;
            *) exit ;;
        esac
    done
}

case "$*" in
    on|y|e*)  on ;;
    off|n|d*) off ;;
    menu|'') loop ;;
    *)
        echo "Usage: $0"
        echo "       $0 enable/disable" ;;
esac
