#!/bin/sh

layout=$(setxkbmap -query | grep layout | awk '{ print $2 }')

setlayout() {
	setxkbmap -layout "$@"
}

n_us() { setlayout fr; }
n_fr() { setlayout il; }
n_il() { setlayout us; }

b_us() { setlayout il; }
b_fr() { setlayout us; }
b_il() { setlayout fr; }

next() { "n_$layout"; }
prev() { "b_$layout"; }

# Only one layout at a time, please.
if echo "$layout" | grep -q ,; then
    layout="$(echo "$layout" | sed 's/,.*$//')"
fi

case "$*" in
    next) next ;;
    prev) prev ;;
    "") echo "$layout" ;;
    *)
        echo "Usage: layout"
        echo "       layout [next/prev]"
        ;;
esac
