#!/bin/sh

layout=$(setxkbmap -query | grep layout | awk '{ print $2 }')

setlayout() {
	setxkbmap -layout "$*"
	pgrep -x sway && swaymsg input '*' xkb_layout "$*"
}

n_us() { setlayout ca; }
n_ca() { setlayout ru; }
n_ru() { setlayout us; }

b_us() { setlayout ru; }
b_ca() { setlayout us; }
b_ru() { setlayout ca; }

next() { "n_$layout"; }
prev() { "b_$layout"; }

# Only one layout at a time, please.
if echo "$layout" | grep -q ,; then
    layout="$(echo "$layout" | sed 's/,.*$//')"
fi

case "$*" in
    next) next ;;
    prev) prev ;;
    "") echo "$layout" ;;
    *)
        echo "Usage: layout"
        echo "       layout [next/prev]"
        ;;
esac
