#!/bin/sh

_sh() {
	shellcheck "$1"
}

_c() {
	cppcheck -q "$1"
	splint +quiet +weak +posixlib -syntax -retvalother "$1"\
	    | grep -r '< Location unknown >'
}

_cpp() {
	cppcheck "$1"
}

_err() {
	echo "$0: $*" > /dev/stderr
}

_recurse() {
	for f in $(find "$1" -type f | sed 's/^\.\///' | grep -v .git); do
		lint "$f"
	done
}

while [ "$1" ]; do
	if [ -d "$1" ]; then
		_recurse "$1"
	else
		wc "$1"
		case $1 in
			# I don't know how to lint these.

			Makefile|makefile|GNUmakefile) ;;
			tags) ;;

			*.sh) _sh "$1" ;;
			*.tex)
				sed -E 's/^\\input.*$//g;s/\\[a-zA-Z]+//g' "$1" > /tmp/spell
				spell -d $HOME/.spell -n /tmp/spell
				rm /tmp/spell ;;
			*.md|*.txt) spell "$1" ;;
			*.htm|*.html) sed 's/<[^<]*>//g' "$1" | spell ;;
			*.c|*.h) _c "$1" ;;
			*.cc|*.cpp|*.hpp) _cpp "$1" ;;
			*.lua) luacheck "$1" ;;
			*.*) _err "no default linter for $1";;
			*) _sh "$1" ;;
		esac
	fi
	shift
done
