#!/bin/sh

_sh() {
	shellcheck "$1"
}

_c() {
	cppcheck "$1"
}

_cpp() {
	cppcheck "$1"
}

_err() {
	echo "$0: $*" > /dev/stderr
}

_recurse() {
	for f in $(find "$1" -type f | sed 's/^\.\///' | grep -v .git); do
		lint "$f"
	done
}

while [ "$1" ]; do
	if [ -d "$1" ]; then
		_recurse "$1"
	else
		case $1 in
			# I don't know how to lint these.

			Makefile|makefile|GNUmakefile) ;;
			tags) ;;

			*.sh) _sh "$1" ;;
			*.md|*.txt) wc "$1" ;;
			*.c|*.h) _c "$1" ;;
			*.cc|*.cpp|*.hpp) _cpp "$1" ;;
			*.lua) luacheck "$1" ;;
			*.*) _err "no default linter for $1";;
			*) _sh "$1" ;;
		esac
	fi
	shift
done
