#!/bin/sh

_sh() {
	shellcheck "$1"
}

_c() {
	cppcheck "$1"
}

_err() {
	echo "$0: $*" > /dev/stderr
}

while [ "$1" ]; do
	case $1 in
		*.sh) _sh "$1" ;;
		*.c) _c "$1" ;;
		*.lua) luacheck "$1" ;;
		*.*) _err "no default linter for $1";;
		*) _sh "$1" ;;
	esac
	shift
done
