#!/bin/sh

extract() {
    for f in "$@"; do
        # shellcheck disable=2016
        [ -f "$f" ] && {
            echo '```'
            sed -e 's|^\W*/\*$|```|' -e 's|^\W* \*/$|```|' -e 's/^\W* \* //' -e 's/^\W* \*$//' "$f"
            echo '```'
        }
    done
}

superfluous() {
    # shellcheck disable=2016
    [ "$(sed 2q < "$*" | uniq)" = '```' ] && sed -i '1,2d' "$*"
}

tmpfile=docs.tmp

mkdocs() {
    extract "$@" > $tmpfile
    superfluous $tmpfile
    [ -f docs_template.html ] && template="--template=docs_template.html"
    pandoc --toc -s $template $tmpfile -o docs.html
    rm $tmpfile
}

mkdocs "$@"
true # to appease Make
