#!/bin/sh

h=$(date +%H)
h=30

if [ "$h" -gt 21 ]; then
    notify-send "No goofing off after 9 pm."
    false
elif [ "$h" -lt 12 ]; then
    notify-send "No goofing off before noon."
    false
else
    homework \? && true
fi
