#!/bin/sh

MAXAGE=86400 # Seconds in a day.
OLD=$(($(date +%s) - MAXAGE))

ARGS=

add_arg() {
	if [ "$ARGS" ]; then
		ARGS="${ARGS},$1"
	else
		ARGS="$1"
	fi
}

new_only() {
	awk -F'\t' "\$1>$OLD"
}

while [ "$1" ]; do
	case $1 in
		new) NEW=1 ;;
		timestamp) add_arg 1 ;;
		title) add_arg 2 ;;
		link) add_arg 3 ;;
		content) add_arg 4 ;;
		content-type) add_arg 5 ;;
		id) add_arg 6 ;;
		author) add_arg 7 ;;
		enclosure) add_arg 8 ;;
		*) echo "$1: unknown argument.";
	esac
	shift
done

if [ "$NEW" ]; then
	if [ "$ARGS" ]; then
		new_only | cut -f "$ARGS"
	else
		new_only
	fi
else
	if [ "$ARGS" ]; then
		cut -f "$ARGS"
	else
		cat
	fi
fi
