#!/bin/sh -e

TMPF="$(mktemp)"

bye() {
	rm "$TMPF"
}

trap bye KILL EXIT TERM

md() {
	markdown -ffootnote
}

htm() {
	title="$(sed '1d;2s/^ *//;q' "$1")"
	subtitle="$(sed '1,2d;3s/^ *//;q' "$1")"
	date="$(sed '1s/^ *//;q' "$1")"
	body="$(sed -e '1,3d;s/^         *\(.*\)$/## \1/'\
		-e 's/^(\([^()]*\)):$/<p class="section">\1<\/p>/' "$1" | md)"

	cat << EOF
<!DOCTYPE html>

<html lang="en">
	<head>
		<title>$title</title>
		<meta charset="UTF-8" />
		<style>$(min < .css)</style>
	</head>

	<body>
		<main>
			<article>
				<header>
					<p class="date">$date</p>
					<h1 class="title">$title</h1>
$(if [ "$subtitle" ]; then echo "\t\t\t\t\t<p class=\"subtitle\">$subtitle</p>"; fi)
				</header>

$body
			</article>
		</main>
	</body>
</html>
EOF
}

outf() {
	echo "$*" | sed -Ee 's/\.(txt|md)$//' -e 's/$/.htm/'
}

build() {
	for f in $(find -type f -name '*.txt'); do
		of="$(outf "$f")"
		if [ "$of" != "$f" ]; then
			echo "$f -> $of"
			htm "$f" > "$(outf "$f")"
		fi
	done
}

rebuild() {
	rm -v $(find -type f -name '*.txt' | sed 's/txt$/htm/')
	build
}

modified() {
	if [ "$(find -type f -name '*.htm')" ]; then
		tar cz $(find -type f -name '*.htm') > site.tar.gz
	fi
}

pline=0
build
modified
inotifywait -qmr . | while read line; do
	[ "$pline" = "$line" ] && continue

	event="$(echo "$line" | cut -d' ' -f2)"
	dir="$(echo "$line" | cut -d' ' -f1)"
	file="$dir$(echo "$line" | cut -d' ' -f3)"
	ofile="$(outf "$file")"

	pline="$line"

	if [ "$file" = .css ]; then
		case "$event" in
			MODIFY|MOVED_TO|CREATE)
				rebuild
				modified ;;
		esac
	elif [ "$ofile" != "$file.htm" ] && [ "$ofile" != "$file" ]; then
		case "$event" in
			MODIFY|MOVED_TO|CREATE)
				echo "$file -> $ofile <- $line"
				htm "$file" > "$ofile"
				modified ;;
			DELETE|MOVED_FROM|DELETE_SELF|MOVE_SELF)
				rm -v "$ofile"
				modified ;;
		esac
	fi
done
