#!/bin/sh

www() {
	if [ "$BROWSER" ]; then
		"$BROWSER" "$1"
	elif [ "$DISPLAY" ]; then
		surf "$1"
	else
		lynx -nopause "$1"
	fi
}

if [ "$1" ]; then
	x="$1"
	shift
	q="$*"
	case "$x" in
		w|wiki)
			www "https://en.wikipedia.org/wiki/Special:Search?search=$q"
			;;
		d|ddg)
			www "https://lite.duckduckgo.com/lite?q=$q"
			;;
		g|goo)
			www "https://www.google.com/search?hl=en&q=$q"
			;;
		y|yt)
			www "https://youtube.com/results?search_query=$q"
			;;
		tr|trans)
			www "https://translate.google.com/?q=$q&sl=en"
			;;
	esac
fi
