#!/bin/sh

PID=$$

# Screen dimensions.

getdimens() {
    xrandr | awk '/*/ { sub("x", " ", $1); print $1; }'
}

getdimen() {
    getdimens | awk "{ print \$$1 }"
}

MARGIN=50
WIDTH=$(($(getdimen 1) - (MARGIN * 2)))
HEIGHT=15

# Is a compositor running?

has_compositor() {
    pgrep -x compton > /dev/null 2> /dev/null
}

# Colours/fonts.

THEME=$*

MENU_FONT="${MENU_FONT:-Charter:size=10}"
MENU_OPACITY="${MENU_OPACITY:-00}"

setcolors() {
    if [ "$THEME" = light ]; then
        MENU_BG="${MENU_BG:-e6e6e6}"
        MENU_FG="${MENU_FG:-191919}"
    else
        MENU_BG="${MENU_BG:-191919}"
        MENU_FG="${MENU_FG:-e6e6e6}"
    fi

    if has_compositor; then
        MENU_BG="${MENU_OPACITY}$MENU_BG"
    fi
}

setcolors

bar() {
    [ "$1" = b ] && bottom='-b'
    lemonbar "$@" -g "${WIDTH}x${HEIGHT}+${MARGIN}" -d -f "$MENU_FONT" "#$MENU_BG" -F "#$MENU_FG" "$bottom"
}

status() {
    delay=$1
    left=$2
    mid=$3
    right=$4
    b=$5
    while ps "$PID" > /dev/null; do
        echo "%{l}$($left)%{c}$($mid)%{r}$($right)"
        sleep "$delay"
    done | bar "$b"
}

# Various status commands.

_time() { date +'%T'; }
_date() { date +'%D'; }

_layout() { layout | tr '[:lower:]' '[:upper:]'; }

# TODO: integrate with headphones
vol() {
    if amixer get Headphone > /dev/null 2> /dev/null; then
        get=Headphone
    else
        get=Master
    fi

    amixer get $get | tr ' ' '\n' | grep % | tr -d '[]' | uniq
}

bat() { acpi | tr ' ' '\n' | grep % | tr -d ','; }

# Top

status 1 '_time' 'mori'    '_date' -b &
status 0 'vol'   '_layout' 'bat'
