#!/bin/sh

PID=$$

MARGIN=15
MARGIN=$(seq -s ' ' $MARGIN | tr -d '0-9')

# Is a compositor running?

has_compositor() {
    pgrep -x compton > /dev/null 2> /dev/null
}

# Colours/fonts.

MENU_FONT="${MENU_FONT:-Charter:size=10}"

MENU_BG=$(theme get bg)
MENU_FG=$(theme get fg)
MENU_OPACITY=$(theme get opacity)

if has_compositor; then
    MENU_BG="${MENU_OPACITY}$MENU_BG"
fi

bar() {
    [ "$1" = b ] && bottom='-b'
    lemonbar "$@" -d -f "$MENU_FONT" -B "#$MENU_BG" -F "#$MENU_FG" "$bottom"
}

status() {
    delay=$1
    left=$2
    mid=$3
    right=$4
    b=$5
    while ps "$PID" > /dev/null; do
        echo "%{l}${MARGIN}$($left)%{c}$($mid)%{r}$($right)${MARGIN}"
        sleep "$delay"
    done | bar "$b"
}

# Various status commands.

_time() { date +'%T'; }
_date() { date +'%D'; }

_layout() { layout | tr '[:lower:]' '[:upper:]'; }

# TODO: integrate with headphones
vol() {
    if amixer get Headphone > /dev/null 2> /dev/null; then
        get=Headphone
    else
        get=Master
    fi

    amixer get $get | tr ' ' '\n' | grep % | tr -d '[]' | uniq
}

bat() { acpi | tr ' ' '\n' | grep % | tr -d ','; }

# Top

status 1 '_time' 'mori'    '_date' -b &
status 0 'vol'   '_layout' 'bat'
