#!/bin/sh

PID=$$

MARGIN=15
MARGIN=$(seq -s ' ' $MARGIN | tr -d '0-9')

# Is a compositor running?

has_compositor() {
    pidof compton > /dev/null 2> /dev/null
}

# Colours/fonts.

FONT="${FONT:-Linux Libertine O:size=12}"

BG=$(theme get bg)
FG=$(theme get fg)
OPACITY=$(theme get opacity)

if has_compositor && [ "$OPACITY" != ff ]; then
    BG="${OPACITY}$BG"
fi

bar() {
    [ "$1" = b ] && bottom='-b'
    lemonbar "$@" -d -f "$FONT" -B "#$BG" -F "#$FG" "$bottom"
}

status() {
    delay=$1
    left=$2
    mid=$3
    right=$4
    b=$5
    while ps "$PID" > /dev/null; do
        echo "%{l}${MARGIN}$($left)%{c}$($mid)%{r}$($right)${MARGIN}"
        sleep "$delay"
    done | bar "$b"
}

# Various status commands.

_time() { date +'%T'; }
_date() { date +'%D'; }

# TODO: integrate with headphones
vol() {
    if amixer get Headphone > /dev/null 2> /dev/null; then
        get=Headphone
    else
        get=Master
    fi

    amixer get $get | tr ' ' '\n' | grep % | tr -d '[]' | uniq
}

bat() { acpi | tr ' ' '\n' | grep % | tr -d ','; }

# Top

status 1  '_time' 'mori' '_date' -b &
status 0  'vol'   'cov'  'bat'
