#!/bin/sh

THEMEFILE=/tmp/theme

themes() {
    echo light
    echo dark
}

statusbar()
{
    killall status
    killall lemonbar
    status "$THEME" &
}

wallpaper()
{
    case "$THEME" in
        light) feh --bg-fill ~/pics/LightWallpaper ;;
        dark)  feh --bg-fill ~/pics/DarkWallpaper  ;;
    esac
}

term()
{
    BINDIR="$HOME/bin" make install -C "$HOME/src/repos/UI/st/$THEME"
}

notifications()
{
    rm ~/.config/dunst/dunstrc
    link "$HOME/src/repos/UI/dunst/themes/dunstrc_$THEME" ~/.config/dunst/dunstrc
    killall dunst
    dunst &
}

rofi()
{
    sed -i "s/rofi\\.theme:.*$/rofi.theme:         $THEME.rasi/" ~/.config/rofi/config
}

spotify()
{
    if [ "$THEME" = light ]; then
        spicetify config current_theme DefaultLight
        spicetify update
    else
        spicetify config current_theme DefaultDark
        spicetify update
    fi
}

gtk() {
    export GTK_THEME="oomox-$THEME"
    export ICON_THEME="oomox-$THEME"
    export FONT="Charter 10"

    # Set GTK theme via xsettings.
    xfconf-query -c xsettings -p /Net/ThemeName -s "$GTK_THEME"
    xfconf-query -c xsettings -p /Net/IconThemeName -s "$ICON_THEME"
    xfconf-query -c xsettings -p /Gtk/FontName -s "$FONT"
}

switchto() {
    export THEME="$*"
    echo "$THEME" > "$THEMEFILE"
    gtk
    term
    rofi
    wallpaper
    statusbar
    notifications
    spotify
}

case $* in
    light) switchto light ;;
    dark)  switchto dark  ;;
    menu)  $0 "$(themes | menu)" ;;
    list)  themes ;;
    "")    cat "$THEMEFILE" ;;
    *)
        echo "Usage: $0 <theme>"
        echo "       $0 list"
        echo "       $0 menu"
        ;;
esac
