#!/bin/sh
#
# Simple command to get (attributes of) the current theme.
#
# If you want to add a new theme, you must add a corresponding entry in
# ~/src/ui/themes, ~/src/ui/st/themes, ~/src/ui/dunstw, ~/.config/rofi,
# ~/.config/spicetify/Themes, and a new GTK+ theme called oomox-<theme>
#

THEMEFILE=/tmp/theme
THEMEDIR=$HOME/src/ui/themes

themes() {
    cd ~/src/ui/themes || exit
    for f in *; do
        echo "$f"
    done
}

statusbar() {
    killall status
    killall lemonbar
    status "$THEME" &
}

wallpaper() {
    feh --bg-fill "$HOME/pics/wall/$THEME"
}

term() {
    export BINDIR="$HOME/bin"
    (
        cd "$HOME/src/ui/st" || return
        make clean
        make CFLAGS="-Ithemes/$THEME" install
    )
}

notifications() {
    killall dunst
    install -D "$HOME/src/ui/dunst/$THEME" ~/.config/dunst/dunstrc
    dunst &
}

rofi() {
    sed -i "s/rofi\\.theme:.*$/rofi.theme:         $THEME.rasi/" ~/.config/rofi/config
}

spotify() {
    spicetify config current_theme "$THEME"
    spicetify update
}

gtk() {
    export GTK_THEME="oomox-$THEME"
    export ICON_THEME="oomox-$THEME"
    export FONT="Charter 10"

    # Set GTK theme via xsettings.
    xfconf-query -c xsettings -p /Net/ThemeName -s "$GTK_THEME"
    xfconf-query -c xsettings -p /Net/IconThemeName -s "$ICON_THEME"
    xfconf-query -c xsettings -p /Gtk/FontName -s "$FONT"
}

switchto() {
    export THEME="$*"
    echo "$THEME" > "$THEMEFILE"
    term &
    gtk
    rofi
    wallpaper
    statusbar
    notifications
    spotify
}

case $1 in
    s|set) [ -f "$THEMEDIR/$2" ] && switchto "$2" ;;
    m|menu)
        opt=$(themes | menu)
        [ "$opt" ] && $0 set "$opt" ;;
    l|list) themes ;;
    "")    cat "$THEMEFILE" ;;
    g|get) grep "^$2" "$THEMEDIR/$($0)" | awk '{ print $2 }' ;;
    *)
        echo "Usage: $0 <theme>"
        echo "       $0 list"
        echo "       $0 menu"
        ;;
esac
