#!/bin/sh
#
# Simple command to set the current theme, or view attributes OF said theme.
#

THEMEFILE=/tmp/theme
THEMEDIR=$HOME/src/ui/themes

themes() {
	cd ~/src/ui/themes || exit
	for f in *; do
		echo "$f"
	done
}

statusbar() {
	killall status
	killall lemonbar
	status "$THEME" &
}

wallpaper() {
	feh --bg-fill "$HOME/pics/wall/$THEME"
}

term() {
	export BINDIR="$HOME/bin"
	(
		cd "$HOME/src/ui/st" || return
		make clean
	make THEME="-DTHEME='\"$THEME\"' -DFONT='\"$($0 g termfont)\"' -DFGCOLOR='\"#$FG\"' -DBGCOLOR='\"#$BG\"'" install
	)
}

dmenu() {
	(
		cd "$HOME/src/ui/dmenu" || return
		make clean
		make PREFIX="$HOME" THEME="-DTHEME='\"$THEME\"' -DFONT='\"$($0 g barfont)\"' -DFGCOLOR='\"#$FG\"' -DBGCOLOR='\"#$BG\"'" install
	)
}

notify() {
	killall dunst
	sed -i "s/foreground = .*$/foreground = \"#$FG\"/" ~/.config/dunst/dunstrc
	sed -i "s/background = .*$/background = \"#$BG\"/" ~/.config/dunst/dunstrc
	dunst &
}

rofi() {
	sed -i "s/normal-background: .*;$/normal-background: #$BG;/" ~/.config/rofi/theme.rasi
	sed -i "s/normal-foreground: .*;$/normal-foreground: #$FG;/" ~/.config/rofi/theme.rasi
	sed -i "s/font: .*;$/font: \"$($0 g font)\";/" ~/.config/rofi/theme.rasi
}

cwm() {
	sed -i "s/^color menubg.*$/color menubg '#$BG'/" ~/.cwmrc
	sed -i "s/^color font.*$/color font '#$FG'/" ~/.cwmrc
	sed -i "s/^color menufg.*$/color menufg '#$FG'/" ~/.cwmrc
	sed -i "s/^color selfont.*$/color selfont '#$BG'/" ~/.cwmrc
	pgrep cwm && pkill -SIGHUP cwm
}

spotify() {
	(
		cd ~/.config/spicetify/Themes/theme/ || return
		cp ~/.config/spicetify/Themes/color.ini color.ini
		sed -i "s/FG/$FG/" color.ini
		sed -i "s/BG/$BG/" color.ini
		sed -i "s/font-family: .*;$/font-family: \"$($0 g font | awk '{print $1}')\";/" user.css
	)
	spicetify update
}

gtk_set() {
	sed -i "s|^$1.*|$1 \"$2\"|" ~/.xsettingsd
}

gtk() {
	gtk_set Net/ThemeName	 "$(theme get gtk)"
	gtk_set Net/IconThemeName "$(theme get icon)"
	gtk_set Gtk/FontName	  "$(theme get font)"

	killall xsettingsd
	xsettingsd &
}

switchto() {
	export THEME="$*"
	echo "$THEME" > "$THEMEFILE"

	FG="$($0 g fg)"
	BG="$($0 g bg)"

	term &
	dmenu &
	rofi &
	cwm &
	notify &
	spotify &
	gtk
	wallpaper
	statusbar
}

case $1 in
	s|set) [ -f "$THEMEDIR/$2" ] && switchto "$2" ;;
	m|menu)
		opt=$(themes | menu)
		[ "$opt" ] && $0 set "$opt" ;;
	l|list) themes ;;
	"")	cat "$THEMEFILE" ;;
	g|get) grep "^$2" "$THEMEDIR/$($0)" | awk '{ $1=""; print $0 }' | xargs ;;
	*)
		echo "Usage: $0 <theme>"
		echo "	   $0 list"
		echo "	   $0 menu"
		;;
esac
