#!/bin/sh -e
#
# Convert plain text containing Unicode characters to one more usable by
# ASCII systems.
#

txtify() {
	sed -Ee 's/[“”]/"/g'\
	     -e "s/[‘’]/'/g"\
	     -e 's/—/---/g'\
	     -e 's/–/--/g'\
	     -e 's/  ([^ ])/ \1/g'\
	     -e 's/ *(---) */\1/g'\
	     -e 's/\. /.  /g'\
	     -e 's/: /:  /g'\
	     -e 's/; /;  /g'\
	     -e 's/\? /?  /g'\
	     -e 's/! /!  /g'\
	     | fmt -w72 -g72
}

if [ "$1" ]; then
	while [ "$1" ]; do
		txtify < "$1"
		shift
	done
else
	txtify
fi
