#!/bin/sh

src="$1"
dir="$(mktemp -d)"
fil="$(mktemp)"
pdf="$dir/$(basename "$fil").pdf"
mv "$fil" "$fil.tex"
fil="$fil.tex"
pdfpid=0

build() {
	bib "${HOME}/docs/bib/biblio" "${HOME}/docs/bib/style" "$src" > "$fil"
	pdftex -output-directory "$dir" "$fil"
}

rebuild() {
	build
	kill -HUP "$pdfpid"
}

goodbye() {
	kill "$pdfpid"
}

cleanup() {
	rm -rv "$dir" "$fil"
}

trap rebuild HUP
trap goodbye INT TERM
trap cleanup EXIT

build
mupdf "$pdf" &
pdfpid="$!"

while kill -0 "$pdfpid"; do
	wait
done
