#!/bin/sh

if [ "$DISPLAY" ]; then
	# shellcheck disable=SC2063
	h=900
	if command -v xrandr > /dev/null; then
		H=$(xrandr | grep '\*' | sed 's/x.*$//' | tr -d ' ')
	else
		H=1080
	fi

	mpv --ytdl-format="bestvideo[height<=?${H}]+bestaudio/best"\
	    --force-window=immediate --autofit=$h "$*" &
else
	mpv --vo=drm "$*"
fi
