#!/bin/sh
#
# A hacky little shell script to yank files from the SCP
# foundation's servers, clean them up a little, and dump
# them into a text file with lynx(1) before viewing them.
#

SITE=http://scp-wiki.net
LANG=en
SCPD=~/docs/scp

_clean() {
	hxselect '#page-content' |\
	hxnormalize -x |\
	hxremove .footer-wikiwalk-nav |\
	hxremove .info-container |\
	hxremove .page-rate-widget-box |\
	hxremove .scp-image-block
}

_convert() {
	lynx --stdin --dump
}

_process() {
	_clean | _convert
}

_upper() {
	echo "$*" | tr '[:lower:]' '[:upper:]'
}

_fetch() {
	echo "SERVER LOOKUP FOR $(_upper "$1")..."
	mkdir -p ${LANG}
	wget -q "${SITE}/$1" -O- | _process > "${LANG}/$1"
	[ "$(cat "${LANG}/$1")" ] || (rm "${LANG}/$1"; false)
}

_view() {
	cd ${SCPD} || return 1
	[ -f "${LANG}/$1" ] || _fetch "$1" || return 1
	${PAGER:-less -rf} "${LANG}/$1"
}

while [ "$1" ]; do
	x="$1"
	case $x in
		en|english)
			LANG=en
			SITE=http://scp-wiki.net ;;
		fr|french|francais)
			LANG=fr
			SITE=http://fondationscp.wikidot.com ;;
		*)
			(echo "$x" | grep -q '^[0-9]*$') && x="scp-$x"
			_view "$x" || echo "$(_upper "$x"): SCP NOT FOUND" ;;
	esac
	shift
done
