#!/bin/sh

DIR="$(mktemp -d)"
echo "created directory '${DIR}'"

FILE="$1"

PDFPID=0

goodbye() {
	kill $PDFPID
}

cleanup() {
	echo 'EXIT received.  Cleaning up...'
	rm -rv "${DIR}"
}

rebuild() {
	echo 'SIGHUP received.  Rebuilding...'
	pdftex -halt-on-error "$(basename "$FILE")"
	kill -HUP "$PDFPID"
}

trap rebuild HUP
trap goodbye INT TERM
trap cleanup EXIT

ln -v "$FILE" "${DIR}"
cd "${DIR}" || exit
pdftex -halt-on-error "$(basename "$FILE")"

mupdf *.pdf &
PDFPID=$!

while kill -0 $PDFPID; do
	wait
done
