#!/bin/sh

if [ "$DISPLAY" ]; then
    mpv --ytdl-format 'bestvideo[height<=?1080]+bestaudio/best' --force-window=immediate --autofit=900 "$*" &
else
    mpv --vo=drm --ytdl-format 'bestvideo[height<=?1080]+bestaudio/best' --force-window=immediate --autofit=900 "$*"
fi
